#!/bin/sh
#OPENMPI JOB
# --ntasks=x to give the number of mpi process
#SBATCH --ntasks=1
# asking time could be in minute 120 or 2:00:00  or 1-00:00:00(24H)
#SBATCH --time 24:00:00
#SBATCH --mem=20GB

# to debug script could be interessant to have
set -x
# purging all module to be sure to not having interferaence with current environnement
module purge
# loading only needed module for sample
module load python/meso-3.8
# execute my program
python run_pisco.py